robot_node:
  ros__parameters:
    robot_id: 'AMR_01'
    wheel_separation: 0.35
    wheel_radius: 0.05
    invert_left_motor: false
    invert_right_motor: true

odometry_node:
  ros__parameters:
    wheel_separation: 0.35
    wheel_radius: 0.05
    odom_frame: 'odom'
    base_frame: 'base_link'
    invert_left_motor: false
    invert_right_motor: false

robot_state_publisher:
  ros__parameters:
    use_sim_time: false